#include "../components/filters/statistics/statisticsPlugin.hpp"

KRELL_INSTITUTE_CBTF_REGISTER_FACTORY_FUNCTION(ValueToStatistics<long double>)
KRELL_INSTITUTE_CBTF_REGISTER_FACTORY_FUNCTION(StatisticsAggregator<long double>)
KRELL_INSTITUTE_CBTF_REGISTER_FACTORY_FUNCTION(ConvertStatisticsToPacket<long double>)
KRELL_INSTITUTE_CBTF_REGISTER_FACTORY_FUNCTION(ConvertPacketToStatistics<long double>)
KRELL_INSTITUTE_CBTF_REGISTER_FACTORY_FUNCTION(CreateValIdPair<long double>)
KRELL_INSTITUTE_CBTF_REGISTER_FACTORY_FUNCTION(DisplayStatistics<long double>)
